version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${DOCKERHUB_NAME}/ui:${VERSION_UI}
    ports:
      - ${PORT_UI:-9292}:9292/tcp
    networks:
      - front_net
      - back_net
  post:
    build: ./post-py
    image: ${DOCKERHUB_NAME}/post:${VERSION_POST}
    networks:
      - back_net
  comment:
    build: ./comment
    image: ${DOCKERHUB_NAME}/comment:${VERSION_COMMENT}
    networks:
      - back_net

volumes:
  post_db:

networks:
  front_net:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_FRONT}
  back_net:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_BACK}
